apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chatapp.fullname" . }}-backend
  labels:
    app.kubernetes.io/name: {{ include "chatapp.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: backend
spec:
  {{- if .Values.backend.persistence.enabled }}
  strategy:
    type: Recreate
  {{- else }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  {{- end }}
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "chatapp.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "chatapp.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: backend
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- end }}
      {{- if .Values.backend.persistence.enabled }}
      volumes:
        - name: backend-data
          persistentVolumeClaim:
            claimName: {{ if .Values.backend.persistence.existingClaim }}{{ .Values.backend.persistence.existingClaim }}{{ else }}{{ include "chatapp.fullname" . }}-backend-pvc{{ end }}
      {{- end }}
      containers:
        - name: backend
          image: "{{ .Values.image.registry }}/{{ .Values.image.backend.repository }}:{{ .Values.image.backend.tag }}"
          imagePullPolicy: {{ .Values.image.backend.pullPolicy }}
          ports:
            - containerPort: {{ .Values.backend.port }}
              name: http
          env:
            {{- range $k, $v := .Values.backend.env }}
            - name: {{ $k }}
              value: "{{ $v }}"
            {{- end }}
            {{- range $k, $v := .Values.backend.secretEnv }}
            - name: {{ $k }}
              valueFrom:
                secretKeyRef:
                  name: {{ include "chatapp.fullname" $ }}-backend-secrets
                  key: {{ $k | lower }}
            {{- end }}
          {{- if .Values.backend.persistence.enabled }}
          volumeMounts:
            - name: backend-data
              mountPath: {{ .Values.backend.persistence.mountPath }}
          {{- end }}
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "chatapp.fullname" . }}-backend
  labels:
    app.kubernetes.io/name: {{ include "chatapp.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: backend
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "chatapp.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: backend
  ports:
    - name: http
      port: 80
      targetPort: {{ .Values.backend.port }}
