apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chatapp.fullname" . }}-backend-secrets
type: Opaque
data:
  {{- range $k, $v := .Values.backend.secretEnv }}
  {{ $k | lower }}: {{ $v | b64enc }}
  {{- end }}

